site_name: dagster-odp
site_url: https://dagster-odp.github.io/docs
theme:
  name: material
  features:
    - content.code.copy
plugins:
  - glightbox
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/overview.md
    - Quickstart: getting-started/quickstart.md
  - Tutorials:
    - Overview: tutorials/tutorials.md
    - Weather Tutorial: tutorials/weather_tutorial.md
    - Chess Tutorial Part 1: tutorials/chess_part_1.md
    - Chess Tutorial Part 2: tutorials/chess_part_2.md
    - Chess Tutorial Part 3: tutorials/chess_part_3.md
  - Concepts:
    - Overview: concepts/concepts.md
    - Tasks and Assets: concepts/tasks_and_assets.md
    - Resources: concepts/resources.md
    - Automation: concepts/automation.md
    - Configuration: concepts/configuration.md
    - Generating Definitions: concepts/definitions.md
  - Integrations:
    - Overview: integrations/integrations.md
    - DLT: integrations/dlt.md
    - DBT: integrations/dbt.md
    - Soda: integrations/soda.md
  - Reference:
    - Overview: reference/reference.md
    - Dagster Config: reference/dagster_config.md
    - Workflow Config: reference/workflow_config.md