site_name: Dagster ODP
site_url: https://mydomain.org/docs
theme:
  name: material
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
nav:
  - Getting Started:
    - Overview: getting-started/overview.md
    - Quickstart: getting-started/quickstart.md
  - Tutorials: tutorials.md
  - Concepts:
    - Overview: concepts/concepts.md
    - Workflow config: concepts/workflow_config.md
    - Dagster config: concepts/dagster_config.md
    - Tasks: concepts/tasks.md
    - Resources: concepts/resources.md
    - Sensors: concepts/sensors.md
  - Reference:
    - Overview: reference/reference.md
    - Workflows: reference/workflows.md
    - Dagster Config: reference/dagster_config.md